# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

build_annoy <- function(mat, ntrees, fname, dtype) {
    .Call(`_BiocNeighbors_build_annoy`, mat, ntrees, fname, dtype)
}

build_hnsw <- function(mat, nlinks, ef_construct, fname, dtype) {
    .Call(`_BiocNeighbors_build_hnsw`, mat, nlinks, ef_construct, fname, dtype)
}

build_vptree <- function(Mat, dtype) {
    .Call(`_BiocNeighbors_build_vptree`, Mat, dtype)
}

find_annoy <- function(to_check, ndims, fname, search_mult, dtype, nn, get_index, get_distance) {
    .Call(`_BiocNeighbors_find_annoy`, to_check, ndims, fname, search_mult, dtype, nn, get_index, get_distance)
}

find_hnsw <- function(to_check, vals, fname, ef_search, dtype, nn, get_index, get_distance) {
    .Call(`_BiocNeighbors_find_hnsw`, to_check, vals, fname, ef_search, dtype, nn, get_index, get_distance)
}

find_kmknn <- function(to_check, X, clust_centers, clust_info, dtype, nn, get_index, get_distance) {
    .Call(`_BiocNeighbors_find_kmknn`, to_check, X, clust_centers, clust_info, dtype, nn, get_index, get_distance)
}

find_vptree <- function(to_check, X, nodes, dtype, nn, get_index, get_distance) {
    .Call(`_BiocNeighbors_find_vptree`, to_check, X, nodes, dtype, nn, get_index, get_distance)
}

query_annoy <- function(query, ndims, fname, search_mult, dtype, nn, get_index, get_distance) {
    .Call(`_BiocNeighbors_query_annoy`, query, ndims, fname, search_mult, dtype, nn, get_index, get_distance)
}

query_hnsw <- function(query, vals, fname, ef_search, dtype, nn, get_index, get_distance) {
    .Call(`_BiocNeighbors_query_hnsw`, query, vals, fname, ef_search, dtype, nn, get_index, get_distance)
}

query_kmknn <- function(query, X, clust_centers, clust_info, dtype, nn, get_index, get_distance) {
    .Call(`_BiocNeighbors_query_kmknn`, query, X, clust_centers, clust_info, dtype, nn, get_index, get_distance)
}

query_vptree <- function(query, X, nodes, dtype, nn, get_index, get_distance) {
    .Call(`_BiocNeighbors_query_vptree`, query, X, nodes, dtype, nn, get_index, get_distance)
}

range_find_kmknn <- function(to_check, X, clust_centers, clust_info, dtype, dist_thresh, get_index, get_distance) {
    .Call(`_BiocNeighbors_range_find_kmknn`, to_check, X, clust_centers, clust_info, dtype, dist_thresh, get_index, get_distance)
}

range_find_vptree <- function(to_check, X, nodes, dtype, dist_thresh, get_index, get_distance) {
    .Call(`_BiocNeighbors_range_find_vptree`, to_check, X, nodes, dtype, dist_thresh, get_index, get_distance)
}

range_query_kmknn <- function(query, X, clust_centers, clust_info, dtype, dist_thresh, get_index, get_distance) {
    .Call(`_BiocNeighbors_range_query_kmknn`, query, X, clust_centers, clust_info, dtype, dist_thresh, get_index, get_distance)
}

range_query_vptree <- function(query, X, nodes, dtype, dist_thresh, get_index, get_distance) {
    .Call(`_BiocNeighbors_range_query_vptree`, query, X, nodes, dtype, dist_thresh, get_index, get_distance)
}

